#FROM flink:1.17.1
FROM flink:1.17.2-scala_2.12

# Install Python and pip
RUN apt-get update -y && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    openjdk-11-jdk && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install PyFlink and other required packages
RUN pip3 install apache-flink==1.17.2 faker

WORKDIR /opt/flink
