

create_project:
	@echo "Creating project..."
	mvn archetype:generate \
	-DgroupId=com.spycloud \
	-DartifactId=flink-app \
	-DarchetypeArtifactId=maven-archetype-quickstart \
	-DinteractiveMode=false
